### postgresql config ###
spring:
    datasource:
        name: TradeCenter_1_0
        url: jdbc:postgresql://192.168.1.9/TradeCenter_1_0
        username: erp7jia2
        password: erp7jia2
        #druid
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.postgresql.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tc.entity

### log setting ###
logging:
  config: classpath:logger/logback.xml
  path: D:/spring-boot-tc-log








